### ISSUE TITLE
尝试在阿里云的机器上使用

### ISSUE THREAD

**Issue by vearne** [yunify/qsfs-fuse#3]
demesg中报如下错误
Apr 10 16:55:12 ecs-hb-hb1-121-42-9-143 kernel: qsfs[31833]: segfault at 236b000 ip 00000033ef889ab3 sp 00007ffd0e958bc8 error 4 in libc-2.12.so[33ef800000+18a000]

**Comment by vearne** [comment]
root@ecs-hb-hb1-121-42-9-143:~$ qsfs ut-bucket01 /qincloud/ -c=/root/.qincloud -d
FUSE library version: 2.8.3
nullpath_ok: 0
unique: 1, opcode: INIT (26), nodeid: 0, insize: 56
INIT: 7.14
flags=0x0000f07b
max_readahead=0x00020000
E0410 17:25:45.466140  1405 Drive.cpp:212] [ERROR] NotFound, QingStorHeadBucket:NotFound(404)
E0410 17:25:45.466606  1405 Operations.cpp:1511] [ERROR] Unable to connect bucket ut-bucket01
   INIT: 7.12
   flags=0x00000011
   max_readahead=0x00020000
   max_write=0x00020000
   unique: 1, success, outsize: 40
Segmentation fault

**Comment by jimhuaang** [comment]
日志显示是找不到bucket.
qsfs 默认zone是pek3a, 需要使用-z指定您的bucket所在zone.

**Comment by vearne** [comment]
非常感谢，问题已经解决了。
