### ISSUE TITLE
什么时候可以支持mac啊

### ISSUE THREAD

**Issue by vearne** [yunify/qsfs-fuse#4]
rt

**Comment by vearne** [comment]
特别期待我的mac本，能有个这样的网盘(主要是对百度云盘不信任)

**Comment by frostyplanet** [comment]
https://gist.github.com/jcaddel/730dc58f4653adf33e4f 可以参考这里说的方式，应该是 s3fs能支持mac 。

s3兼容接口使用示例可以参考这里
https://docs.qingcloud.com/qingstor/s3/examples.html#s3fs

支持mac的网盘产品在做，挂载盘的支持目前在网盘之后。

**Comment by vearne** [comment]
非常感谢
